---
:token: "OKBUDDY"
:owner: 228574821590499329
# In seconds.
:join_threshold: 600 

# dont use this
:debug: true

:servers:
  # Microsoft Community
  150662382874525696:
    :name: "Microsoft Community"
    :blacklist: true
    :hard_blacklist: false
    :modroles:
      # lead moderator
    - 286639672606720000
      # moderator
    - 150878439220576256

  # testing guild
  438781053675634713:
    :blacklist: true
    :hard_blacklist: true
    :modroles:
      # entity
    - 438781385793208330
      # adminstrator
    - 438781500209758218

:blacklist:
- examplebadword

:hard_blacklist:
- examplebadderword
